# todo: need to chnage mongo from cloud to local server in order to avoid using personal cred
services:
  auth-service:
    image: usama019/auth-service:latest
    env_file:
      - "./auth_service/.env"
    ports:
      - 8000:8000

  bug-service:
    image: usama019/bug-service:latest
    env_file:
      - "./bug_service/.env"
    ports:
      - 8001:8001 

  user-service:
    image: usama019/user-service:latest
    env_file:
      - "./user_service/.env"
    ports:
      - 8002:8002 


  comment-service:
    image: usama019/comment-service:latest
    env_file:
      - "./comment_service/.env"
    ports:
      - 8003:8003
